# Generated by Django 3.2.14 on 2022-07-15 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_given', models.CharField(max_length=50, verbose_name='given name')),
                ('name_family', models.CharField(max_length=50, verbose_name='family name')),
                ('phone_mobile', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('relationship', models.CharField(choices=[('MO', 'Mother'), ('FA', 'Father'), ('GM', 'Grandmother'), ('GF', 'Grandfather'), ('SI', 'Sibling'), ('OT', 'Other')], default='OT', max_length=2)),
            ],
            options={
                'ordering': ['name_family', 'name_given'],
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=75)),
                ('suburb', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('phone_fixed', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['street_address', 'suburb', 'city'],
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('postal_address', models.CharField(blank=True, max_length=150, null=True)),
                ('bank_account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('treasurer_name', models.CharField(blank=True, max_length=50, null=True)),
                ('treasurer_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('treasurer_email', models.CharField(blank=True, max_length=50, null=True)),
                ('leader_name', models.CharField(blank=True, max_length=50, null=True)),
                ('leader_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('leader_email', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=50)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.organisation')),
            ],
            options={
                'ordering': ['sub_name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_given', models.CharField(max_length=50, verbose_name='given name')),
                ('name_family', models.CharField(max_length=50, verbose_name='family name')),
                ('membership_type', models.CharField(choices=[('KE', 'Kea'), ('CU', 'Cub'), ('SC', 'Scout'), ('VE', 'Venturer'), ('UK', 'Unknown')], default='UK', max_length=2)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_invested', models.DateField(blank=True, null=True)),
                ('no_longer_attends', models.BooleanField(default=False)),
                ('no_longer_attends_notification', models.DateField(blank=True, null=True)),
                ('caregivers', models.ManyToManyField(related_name='caregivers', to='members.Caregiver')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.family')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.organisation')),
                ('primary_caregiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_caregiver', to='members.caregiver')),
                ('sub_organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.suborganisation')),
            ],
            options={
                'ordering': ['name_family', 'name_given'],
            },
        ),
        migrations.AddField(
            model_name='caregiver',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.family'),
        ),
    ]
