# Generated by Django 3.2.14 on 2022-07-15 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceMapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_reference_used', models.CharField(max_length=128)),
                ('payment_reference_intended', models.CharField(max_length=10)),
                ('payment_origination_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AccountDebt',
            fields=[
                ('accountentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fees.accountentry')),
                ('invoice_reference', models.CharField(max_length=10)),
            ],
            bases=('fees.accountentry',),
        ),
        migrations.CreateModel(
            name='AccountPayment',
            fields=[
                ('accountentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fees.accountentry')),
                ('payment_type', models.CharField(choices=[('AT', 'Automated Payment'), ('TR', 'Bank Transfer'), ('CA', 'Cash'), ('CH', 'Credit'), ('DI', 'Discount'), ('OT', 'Other')], default='OT', max_length=2)),
                ('payment_reference', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('notes', models.CharField(blank=True, max_length=128, null=True)),
            ],
            bases=('fees.accountentry',),
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.organisation')),
            ],
            options={
                'ordering': ['start', 'end'],
            },
        ),
        migrations.CreateModel(
            name='SubYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fees.year')),
            ],
            options={
                'ordering': ['year__organisation__name', 'start', 'end'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received', models.CharField(max_length=100)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.member')),
                ('subyear', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fees.subyear')),
            ],
            options={
                'ordering': ['member__name_family', 'member__name_given', 'subyear__start', 'subyear__end'],
            },
        ),
    ]
